export const API_ENDPOINTS = {
  auth: {
    login: '/auth/login',
    signin: '/auth/signin',
    logout: '/auth/logout',
    logoutall: '/auth/logoutall',
    refresh: '/auth/refresh',
    forgotPassword: '/auth/forgotpassword',
    resetPassword: '/auth/resetpassword',
    verifyEmail: '/auth/verifyemail',
    publicKey: '/auth/publickey',
    me: '/user/me',
    permissions: '/auth/permissions',
    register: '/register',
    // Root level variants
    loginRoot: '/login',
    signinRoot: '/signin',
  },
  users: {
    list: '/user/list',
    detail: (id: string) => `/user/${id}`,
    create: '/user/',
    update: (id: string) => `/user/${id}`,
    delete: (id: string) => `/user/${id}`,
    updateRole: (id: string) => `/user/${id}/role`,
    updatePassword: (id: string) => `/user/${id}/updatepass`,
    logoutall: (id: string) => `/user/${id}/logoutall`,
    me: '/user/me',
    updateMe: '/user/me',
    changeMyPassword: '/user/me/updatepass',
  },
  items: {
    list: '/item/',
    create: '/item/',
    detail: (id: string) => `/item/${id}`,
    update: (id: string) => `/item/${id}`,
    delete: (id: string) => `/item/${id}`,
  },
  customers: {
    list: '/customers',
    detail: (id: string) => `/customers/${id}`,
    create: '/customers',
    update: (id: string) => `/customers/${id}`,
    delete: (id: string) => `/customers/${id}`,
    search: '/customers/search',
  },
  jobs: {
    list: '/jobs',
    detail: (id: string) => `/jobs/${id}`,
    create: '/jobs',
    update: (id: string) => `/jobs/${id}`,
    delete: (id: string) => `/jobs/${id}`,
    status: (id: string) => `/jobs/${id}/status`,
    assign: (id: string) => `/jobs/${id}/assign`,
    board: '/jobs/board',
  },
  quotations: {
    list: '/quotations',
    detail: (id: string) => `/quotations/${id}`,
    create: '/quotations',
    update: (id: string) => `/quotations/${id}`,
    approve: (id: string) => `/quotations/${id}/approve`,
    reject: (id: string) => `/quotations/${id}/reject`,
    pdf: (id: string) => `/quotations/${id}/pdf`,
  },
  purchaseOrders: {
    list: '/purchase-orders',
    detail: (id: string) => `/purchase-orders/${id}`,
    create: '/purchase-orders',
    update: (id: string) => `/purchase-orders/${id}`,
    approve: (id: string) => `/purchase-orders/${id}/approve`,
  },
  products: {
    list: '/products',
    detail: (id: string) => `/products/${id}`,
    create: '/products',
    update: (id: string) => `/products/${id}`,
    delete: (id: string) => `/products/${id}`,
    adjustStock: (id: string) => `/products/${id}/adjust-stock`,
    movements: (id: string) => `/products/${id}/movements`,
    lowStock: '/products/low-stock',
  },
  payments: {
    list: '/payments',
    detail: (id: string) => `/payments/${id}`,
    create: '/payments',
    verify: (id: string) => `/payments/${id}/verify`,
    invoice: (id: string) => `/payments/${id}/invoice`,
  },
  dashboard: {
    stats: '/dashboard/stats',
    revenue: '/dashboard/revenue',
    jobStatus: '/dashboard/job-status',
    topParts: '/dashboard/top-parts',
    reports: '/reports/generate',
    reportsList: '/reports',
    exportReport: '/reports/export',
  },
  documents: {
    list: '/documents',
    detail: (id: string) => `/documents/${id}`,
    upload: '/documents/upload',
    delete: (id: string) => `/documents/${id}`,
    share: (id: string) => `/documents/${id}/share`,
  },
  email: {
    templates: '/email/templates',
    createTemplate: '/email/templates',
    send: '/email/send',
    sendBulk: '/email/send-bulk',
    logs: '/email/logs',
  },
  batch: {
    jobs: '/batch/jobs',
    create: '/batch/jobs',
    trigger: (id: string) => `/batch/jobs/${id}/trigger`,
    history: (id: string) => `/batch/jobs/${id}/history`,
  },
  iot: {
    devices: '/iot/device',
    register: '/iot/devices',
    deviceBuckets: '/iot/devicebuckets',
    location: (id: string) => `/iot/devices/${id}/location`,
    history: (id: string) => `/iot/devices/${id}/history`,
    sensors: (id: string) => `/iot/devices/${id}/sensors`,
    topic: '/iot/topic',
    topicDeviceChart: '/iot/topicdevicechart',
    controls: '/iot/controls',
    control: '/iot/control',
    monitorDeviceGroup: '/iot/monitordevicegroup',
    monitorDeviceChart: '/iot/monitordevicechart',
    senserCharts: '/iot/sensercharts',
    deviceSenserCharts: '/iot/devicesensercharts',
    locationDevice: '/iot/locationdevice',
    alarmDeviceStatus: '/iot/alarmdevicestatus',
    alarmDeviceStatusControl: '/iot/alarmdevicestatuscontrol',
    deviceStatus: '/iot/devicestatus',
    updateDeviceStatus: '/iot/devicestatus',
    deviceConfig: '/iot/deviceconfig',
    updateDeviceConfig: '/iot/updatedeviceconfig',
    deviceIoTData: '/iot/deviceiotdata',
    deviceStats: '/iot/devicestats',
    deviceDataExport: '/iot/devicedataexport',
    deviceDataCleanup: '/iot/devicedatacleanup',
  },
  mqtt: {
    subscriptions: '/mqtt/subscriptions',
    status: '/mqtt/status',
    getTopicData: '/mqtt/gettopicdata',
    deviceControl: '/mqtt/devicecontrol',
    publish: '/mqtt/publish',
    subscribe: '/mqtt/subscribe',
    unsubscribe: '/mqtt/unsubscribe',
  },
  influx: {
    write: '/influx/write',
    query: '/influx/query',
    deviceChart: '/influx/devicechart',
    filters: '/influx/filters',
    statistics: '/influx/statistics',
  },
  alarm: {
    validate: '/alarm/validate',
    validateEn: '/alarm/validate/en',
    validateTh: '/alarm/validate/th',
  },
  reports: {
    scheduleLogs: '/webiot/settings/schedule/logs',
    alarmLogs: '/webiot/settings/alarm/logs',
    logsControl: '/webiot/settings/alarm/logscontrol',
    deviceReport: '/webiot/dashboard/device',
  },
  orders: {
    create: '/orders',
  },
  system: {
    ping: '/ping',
    health: '/health',
    metrics: '/metrics',
    apiMetric: '/apimetric',
    swagger: '/swagger/*',
  },
  wos: {
    orders: '/wos/orders',
    detail: (id: string) => `/wos/orders/${id}`,
    create: '/wos/orders',
    status: (id: string) => `/wos/orders/${id}/status`,
    cancel: (id: string) => `/wos/orders/${id}/cancel`,
  },
  settings: {
    schedules: {
      list: '/settings/listschedulepage',
      detail: (id: string) => `/settings/schedules/${id}`,
      create: '/settings/schedules',
      update: (id: string) => `/settings/updateschedule/${id}`,
      delete: (id: string) => `/settings/schedules/${id}`,
      devicePage: '/settings/scheduledevicepage',
      deviceList: '/settings/listdevicepageallactiveschedule',
      deviceCreate: '/settings/createscheduledevice',
      deviceDelete: '/settings/deletescheduledevice',
      logsPaginate: '/settings/scheduleprocesslogpaginate',
      allSchedules: '/settings/scheduleall',
      updateDayStatus: '/settings/updatescheduledaystatus',
      updateStatus: '/settings/updateschedulestatus',
    },
    locations: {
      list: '/settings/locations',
      detail: (id: string) => `/settings/locations/${id}`,
      create: '/settings/locations',
      update: (id: string) => `/settings/locations/${id}`,
      delete: (id: string) => `/settings/locations/${id}`,
    },
    hardware: {
      list: '/settings/hardware',
      detail: (id: string) => `/settings/hardware/${id}`,
      create: '/settings/hardware',
      update: (id: string) => `/settings/hardware/${id}`,
      delete: (id: string) => `/settings/hardware/${id}`,
    },
    sensors: {
      list: '/settings/sensors',
      detail: (id: string) => `/settings/sensors/${id}`,
      create: '/settings/sensors',
      update: (id: string) => `/settings/sensors/${id}`,
      delete: (id: string) => `/settings/sensors/${id}`,
    },
    nodered: {
      list: '/settings/nodered',
      detail: (id: string) => `/settings/nodered/${id}`,
      create: '/settings/nodered',
      update: (id: string) => `/settings/nodered/${id}`,
      testConnection: (id: string) => `/settings/nodered/${id}/test`,
    },
    lineNotifications: {
      list: '/settings/line-notifications',
      detail: (id: string) => `/settings/line-notifications/${id}`,
      create: '/settings/line-notifications',
      update: (id: string) => `/settings/line-notifications/${id}`,
      delete: (id: string) => `/settings/line-notifications/${id}`,
    },
    smsNotifications: {
      list: '/settings/sms-notifications',
      detail: (id: string) => `/settings/sms-notifications/${id}`,
      create: '/settings/sms-notifications',
      update: (id: string) => `/settings/sms-notifications/${id}`,
      delete: (id: string) => `/settings/sms-notifications/${id}`,
    },
    hosts: {
      list: '/settings/hosts',
      detail: (id: string) => `/settings/hosts/${id}`,
      create: '/settings/hosts',
      update: (id: string) => `/settings/hosts/${id}`,
      delete: (id: string) => `/settings/hosts/${id}`,
    },
    apiSettings: {
      list: '/settings/api-settings',
      detail: (id: string) => `/settings/api-settings/${id}`,
      create: '/settings/api-settings',
      update: (id: string) => `/settings/api-settings/${id}`,
      delete: (id: string) => `/settings/api-settings/${id}`,
    },
    tokens: {
      list: '/settings/tokens',
      detail: (id: string) => `/settings/tokens/${id}`,
      create: '/settings/tokens',
      revoke: (id: string) => `/settings/tokens/${id}`,
    },
  },
  roles: {
    list: '/roles',
    detail: (id: number) => `/roles/${id}`,
    create: '/roles',
    update: (id: number) => `/roles/${id}`,
    delete: (id: number) => `/roles/${id}`,
    permissions: (id: number) => `/roles/${id}/permissions`,
  },
  schedule: {
    schedules: {
      list: '/fullschedule/listschedulepage',
      listAll: '/fullschedule/scheduleall',
      detail: (id: string) => `/fullschedule/${id}`,
      create: '/fullschedule',
      update: (id: string) => `/fullschedule/${id}`,
      delete: (id: string) => `/fullschedule/${id}`,
      setStatus: (id: string) => `/fullschedule/${id}/status`,
      updateDayStatus: (id: string) => `/fullschedule/${id}/day-status`,
      trigger: (id: string) => `/fullschedule/${id}/trigger`,
      devicePage: '/fullschedule/scheduledevicepage',
      deviceList: '/fullschedule/listdevicepageallactiveschedule',
      devices: (id: string) => `/fullschedule/${id}/devices`,
      mapDevices: (id: string) => `/fullschedule/${id}/devices`,
      settings: (id: string) => `/fullschedule/${id}/settings`,
      setSetting: (id: string) => `/fullschedule/${id}/settings`,
      history: (id: string) => `/fullschedule/${id}/history`,
      historyAll: '/fullschedule/history',
      count: '/fullschedule/count',
    },
    groups: {
      list: '/groups',
      detail: (id: string) => `/groups/${id}`,
      create: '/fullschedule/groups',
      update: (id: string) => `/groups/${id}`,
      delete: (id: string) => `/groups/${id}`,
    },
    zones: {
      list: '/zones',
      detail: (id: string) => `/zones/${id}`,
      create: '/zones',
      update: (id: string) => `/zones/${id}`,
      delete: (id: string) => `/zones/${id}`,
    },
    areas: {
      list: '/areas',
      detail: (id: string) => `/areas/${id}`,
      create: '/areas',
      update: (id: string) => `/areas/${id}`,
      delete: (id: string) => `/areas/${id}`,
    },
    report: '/fullschedule/report',
  },
  permissions: {
    list: '/permissions',
  },
};
